//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetShopEntities : DbContext
    {
        public InternetShopEntities()
            : base("name=InternetShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<Client_Table> Client_Table { get; set; }
        public virtual DbSet<Location_Table> Location_Table { get; set; }
        public virtual DbSet<Order_Item_Table> Order_Item_Table { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<Salesman_Table> Salesman_Table { get; set; }
        public virtual DbSet<Status_Order_Item_Table> Status_Order_Item_Table { get; set; }
        public virtual DbSet<Status_Table> Status_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
