//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Table()
        {
            this.Order_Item_Table = new HashSet<Order_Item_Table>();
        }
    
        public int Order_Code { get; set; }
        public Nullable<System.DateTime> Order_Fullfillment { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Client_Code { get; set; }
        public Nullable<int> Salesman_Code { get; set; }
        public Nullable<int> Delivery_Code { get; set; }
    
        public virtual Client_Table Client_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_Table> Order_Item_Table { get; set; }
        public virtual Status_Table Status_Table { get; set; }
        public virtual Salesman_Table Salesman_Table { get; set; }
    }
}
