//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Table()
        {
            this.Order_Item_Table = new HashSet<Order_Item_Table>();
        }
    
        public int Product_Code { get; set; }
        public string Name_Product { get; set; }
        public Nullable<int> Market_Price_Product { get; set; }
        public Nullable<int> Purchase_Price_Product { get; set; }
        public Nullable<System.DateTime> Date_of_Manufacture_Product { get; set; }
        public Nullable<int> Best_Before_Date_Product { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Number_in_Stock { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_Table> Order_Item_Table { get; set; }
    }
}
